---
swagger: "2.0"
info:
  description: "The Allele Calling  service provides an API for converting raw sequence\
    \ data to GFE and HLA allele calls."
  version: "0.0.5"
  title: "Allele Calling Service"
  contact:
    email: "mhalagan@nmdp.org"
  license:
    name: "GNU GENERAL PUBLIC LICENSE"
    url: "https://www.gnu.org/licenses/lgpl.html"
tags:
  - name: "Type Seq"
    description: "Endpoint to annotate and call allele names"
  - name: "Type Align"
    description: "Experimental endpoint for producing annotations with sequence differences"

paths:
  /type_seq:
    get:
      tags:
       - "Type Seq"
      description: "Get HLA and GFE from consensus sequence or GFE notation"
      operationId: "typeseq_get"
      produces:
      - "application/json"
      parameters:
      - name: "locus"
        in: "query"
        description: "Valid HLA locus"
        required: true
        type: "string"
      - name: "sequence"
        in: "query"
        description: "Consensus sequence"
        required: true
        type: "string"
      - name: "imgthla_version"
        in: "query"
        description: "IMGT/HLA DB Version"
        required: false
        type: "string"
        default: "3310"
      - name: "neo4j_url"
        in: "query"
        description: "URL for the neo4j graph"
        required: false
        type: "string"
      - name: "user"
        in: "query"
        description: "Username for the neo4j graph"
        required: false
        type: "string"
      - name: "password"
        in: "query"
        description: "Password for the neo4j graph"
        required: false
        type: "string"
      - name: "verbose"
        in: "query"
        description: "Flag for running service in verbose"
        required: false
        type: "boolean"
      responses:
        200:
          description: "HLA and GFE from consensus sequence"
          schema:
            $ref: "#/definitions/Typing"
        404:
          description: "Failed to generate allele call"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /type_align:
    get:
      tags:
       - "Type Align"
      description: "Get HLA and GFE from consensus sequence or GFE notation"
      operationId: "typealign_get"
      produces:
      - "application/json"
      parameters:
      - name: "locus"
        in: "query"
        description: "Valid HLA locus"
        required: true
        type: "string"
      - name: "sequence"
        in: "query"
        description: "Consensus sequence"
        required: true
        type: "string"
      - name: "imgthla_version"
        in: "query"
        description: "IMGT/HLA DB Version"
        required: false
        type: "string"
        default: "3310"
      - name: "neo4j_url"
        in: "query"
        description: "URL for the neo4j graph"
        required: false
        type: "string"
      - name: "user"
        in: "query"
        description: "Username for the neo4j graph"
        required: false
        type: "string"
      - name: "password"
        in: "query"
        description: "Password for the neo4j graph"
        required: false
        type: "string"
      - name: "verbose"
        in: "query"
        description: "Flag for running service in verbose"
        required: false
        type: "boolean"
      responses:
        200:
          description: "HLA and GFE from consensus sequence"
          schema:
            $ref: "#/definitions/Typing"
        404:
          description: "Failed to generate allele call"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  Error:
    type: "object"
    required:
    - "Message"
    - "gfedb_version"
    - "imgtdb_version"
    - "pygfe_version"
    properties:
      Message:
        type: "string"
      pygfe_version:
        type: "string"
      gfedb_version:
        type: "string"
      imgtdb_version:
        type: "string"
      log:
        type: "array"
        items:
          type: "string"
      type:
        type: "string"
  Typing:
    type: "object"
    properties:
      seqdiff:
        type: "array"
        items:
          $ref: "#/definitions/Seqdiff"
      protdiff:
        type: "array"
        items:
          $ref: "#/definitions/Seqdiff"
      features:
        type: "array"
        items:
          $ref: "#/definitions/Feature"
      gfe:
        type: "string"
      hla:
        type: "string"
      closest_gfe:
        type: "string"
      full_gene_accession:
        type: "integer"
      differences:
        type: "integer"
      status:
        type: "string"
      pygfe_version:
        type: "string"
      gfedb_version:
        type: "string"
      imgtdb_version:
        type: "string"
    example:
      gfe: "HLA-Aw1-1-7-20-10-32-7-1-1-1-6-1-5-3-5-1-1"
      hla: "HLA-A*01:01:01:01"
      G: "HLA-A*01:01:01G"
      lg: "HLA-A*01:01g"
      full_gene_accession: 10093
      closest_gfe: "HLA-Aw1-1-7-20-10-32-7-1-1-1-6-1-5-3-5-1-1"
      differences: 10
      sequence_differences:
      - term: "intron"
        rank: 1
        pos: 10
        ref: "A"
        inseq: "G"
      protdiff:
        pos: 4
        location: "ARD"
        ref: "A"
        inseq: "G"
      status: "novel"
      features:
      - accession: 1
        locus: "HLA-A"
        rank: 1
        term: "exon"
        sequence: "ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG"
      - accession: 2
        locus: "HLA-A"
        rank: 1
        sequence: "ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG"
        term: "exon"
      act_version: "0.0.1"
      gfe_version: "0.0.1"
      gfedb_version: "0.0.1"
  Seqdiff:
    type: "object"
    properties:
      term:
        type: "string"
      rank:
        type: "integer"
      location:
        type: "integer"
      ref:
        type: "string"
      inseq:
        type: "string"
    example:
      term: "intron"
      rank: 1
      pos: 10
      ref: "A"
      inseq: "G"
  Feature:
    type: "object"
    properties:
      accession:
        type: "integer"
      rank:
        type: "integer"
      sequence:
        type: "string"
      term:
        type: "string"
    example:
      accession: 1
      locus: "HLA-A"
      rank: 1
      sequence: "ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG"
      term: "exon"
